### ISSUE TITLE
FormatsCreationDate not found in Assely/Adapter/Post.php on line 13

### ISSUE THREAD

**Issue by mawiswiss** [assely/framework#11]
The following error is thrown, when I try to grab a custom post type and make it available to the view (`'posts' => $team->all()`) inside a Controller:

`Fatal error: Trait 'Assely\Adapters\Traits\FormatsCreationDate' not found in /srv/www/DOMAIN/current/web/app/plugins/assely-framework/src/Assely/Adapter/Post.php on line 13`

**Comment by jedrzejchalubek** [comment]
Ah, typos in namespaces. Fixed :)

**Comment by mawiswiss** [comment]
Oh noo. Haven't noted this ;)
