### ISSUE TITLE
Menu item objects should have `active` status property

### ISSUE THREAD

**Issue by Soean** [assely/framework#15]
I want to check, if I am on the page of an Menu item item_id to style it, like ```.current-menu-item``` in ```wp_nav_menu()```

https://developer.wordpress.org/reference/functions/wp_nav_menu/#current-page-menu-items

**Comment by jedrzejchalubek** [comment]
Done with d9aca5d.

Now, each menu item has `active` property.

```php
$menu_item->active
```

If you want to access menu classes, you can do that by orginal object.

```php
$menu_item->getAdaptee()->classes
```
