### ISSUE TITLE
Refactor Routing and introduce Rewrite component

### ISSUE THREAD

**Issue by jedrzejchalubek** [assely/framework#17]
Currently router is responsible for registering custom rewrite rules. As there is no way to check if similar rule already exist, this often leads to conflicts with rules already registered by WordPress.

Refactoring process include these steps:
- [x] Refactor router itself. His task will be only to switch and run correct actions on url match.
- [x] Routes can be narrowed with Conditional tags with `where` method.
- [x] Create new Rewrite component. API around WordPress Rewrite Rules.
- [x] Create new file where you will be able to register custom rewrite rules (probably src/Http/rewrites.php)
- [x] Write unit tests for Rewrite component
- [x] Write unit tests for Routing component

**Comment by jedrzejchalubek** [comment]
Routing refactoring ready to test with https://github.com/assely/framework/commit/2b708face2ef64c755eb097b4089280c4c44dc31, also documentation roughly updated to reflect new API (https://assely.org/docs/routing).

Still needs some additional tweaks, but it's much faster 🚀

**Comment by mawiswiss** [comment]
Are the conditional tags stripped?

**Comment by jedrzejchalubek** [comment]
Unfortunately yes (for now). I'm not sure if going to implement they back like they where before, because this was unnatural.

Im thinking about implementing it that way:

```php
Route::get('{name}', function($name) {
    $post = Post::type('post')->find($name);
})->where([
    'post' => 'post-slug'
]);
```

On the route matching, items in `where` statement will be additionally checked. For example route above will call `is_single('post-slug')` before returning match status.

What do you think about this?

**Comment by jedrzejchalubek** [comment]
Conditional routes done with 8e3928c and this works pretty neat. Syntax as above, going to update docs :)

**Comment by anoopd** [comment]
Not sure if i am stating it right  .....    once the permalink structure changes , the router will not be working and is just redirecting to homepage  ......  So it should be a new rewrite component right  ?  Another doubt on how this deals with sass files and js ? Anything like elixir ??

**Comment by jedrzejchalubek** [comment]
Router job is only to run specified controllers/closures on url match. Of course this require permalinks settings to be turn on. Naturally, changes in default permalinks structure will affect routes and they need to be updated as well. 

Workflow around adding non-standard urls will be look like this: Register custom rewrite rule with Rewrite component -> Create Route which targets rule added before

Asset files like styles and scripts should be registered with Asset component. Router have nothing to do with this.

**Comment by anoopd** [comment]
I am aware of Asset component , i was asking is there a chance to  'compile' sass out of box or whether should i use something like gulp or grunt to automate tasks  . Ok anyway , thank you .

**Comment by jedrzejchalubek** [comment]
Assely uses Laravel Elixir (wrapper around gulp), it is ready to use from beginning. 

...and I thinking now, we have missing documentation about that. For now I can direct you to the [official Laravel Elixir docs](https://laravel.com/docs/5.3/elixir).

**Comment by marcwieland95** [comment]
Yes, Elixir works out of the box.
Cache Busting isn't working. Would be great if this could be integrated into the Asset component.

**Comment by anoopd** [comment]
Hi , 
       Nice to know Elixir is there  ....... as you said it was not there in docs , thank you

**Comment by jedrzejchalubek** [comment]
@marcwieland95 What you mean by "Cache Busting"?

**Comment by marcwieland95** [comment]
@jedrzejchalubek This [Compiling Assets (Laravel Elixir) - Versioning / Cache Busting](https://laravel.com/docs/5.3/elixir#versioning-and-cache-busting)
