### ISSUE TITLE
Trying to get property of non-object  Adapter.php line 51

### ISSUE THREAD

**Issue by anoopd** [assely/framework#36]
Hi newbie here trying the framework , was just trying to add a menu and i was able to register it but when i tried to render it using 

```blade
<div class="menu--primary">
    @include('menu.nav', [
        'items' => Menu::get('primary')->items()
    ])
</div>
```

and was getting the error "Trying to get property of non-object in Adapter.php line 51 . Any idea on why this happens ?

**Comment by anoopd** [comment]
I am using Bedrock

**Comment by jedrzejchalubek** [comment]
Could you give me content of the `menu.nav` template too?

**Comment by anoopd** [comment]
<div class="menu--primary">
    @include('menu.nav', [
        'items' => Menu::get('primary')->items()
    ])
</div>

This was put in views/menu/nav.blade.php

**Comment by anoopd** [comment]
```blade
<ul>
    @foreach($items as $item)
        <li>
            <a href="{{ $item->link }}">{{ $item->title }}</a>
        </li>
    @endforeach
</ul>
```
in menu/nav.blade.php

**Comment by anoopd** [comment]
i commented out everything in nav.blade.php and still the error persists

**Comment by anoopd** [comment]
PHP 7.0.8 (cli) (built: Jun 26 2016 12:30:44) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0RC3, Copyright (c) 2002-2015, by Derick Rethans

**Comment by jedrzejchalubek** [comment]
If you comment out entire `@include('menu.nav')` error still shows up?

**Comment by anoopd** [comment]
Nope it shows the welcome screen

**Comment by jedrzejchalubek** [comment]
I still cannot reproduce your error. I've made new project with markup form above and everything works fine.

Make sure you don't have any typos. Try to var_dump $items or $item and see what you get.

**Comment by jedrzejchalubek** [comment]
Try also to clear views cache. With `wp assely:clear views` or by deleting `storage/framework/views`

**Comment by anoopd** [comment]
sure will dd $items and $item

**Comment by anoopd** [comment]
Got it !! The error happened since i didnt 'assigned' menu to theme location from WP backend . Now it is working  !!  Thank you for the support  .....  Please let me know how i can support/help you with this project .
