### ISSUE TITLE
Install framework via composer (usage with bedrock)

### ISSUE THREAD

**Issue by mawiswiss** [assely/framework#6]
When trying to install the package with bedrock, we need to add `"minimum-stability": "dev"` to the composer.json inside the `/site` directory.

Note this inside the documentation or match it in the composer.json of assely.

When running `composer require assely/framework`:
_Could not find package assely/framework at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability._

When adding package manually to composer.json ("assely/framework": "^0.1.0"):
_Your requirements could not be resolved to an installable set of packages._

We need to add it this way: "assely/framework": "dev-master" -> add releases inside the repo

**Comment by jedrzejchalubek** [comment]
I don't want to tag any release until framework be "patched" enough for beta.

However, as you point out installation guide tells to use release. I will update docs, thanks.

**Comment by tobeycodes** [comment]
You can specify version with Composer in CLI. In this case

`composer require assely/framework:dev-master`

**Comment by mawiswiss** [comment]
Yes, that's default. For now it's fine, but later we want to specify versions like it was in the docu.
Thanks @jedrzejchalubek, the installation guide is right now.
